### ISSUE TITLE
C2664 error when compiling in VS2017 community

### ISSUE THREAD

**Issue by zdybak** [d3dcoder/d3d12book#14]
I'm trying to get the initial box project going in VS2017 community, I'm getting this error:

Error	C2664	'int MessageBoxA(HWND,LPCSTR,LPCSTR,UINT)': cannot convert argument 2 from 'const wchar_t *' to 'LPCSTR'	dxtest	c:\code\dxtest\boxapp.cpp	101	

Here is the code snippet from boxapp.cpp:
 catch(DxException& e)
    {
        MessageBox(nullptr, e.ToString().c_str(), L"HR Failed", MB_OK);
        return 0;
    }
}

**Comment by JoeSwindell** [comment]
Under the Project menu on the toolbar, go to the Project property page. Under General change the Character Set to Multi-Byte.

**Comment by zdybak** [comment]
Thanks Joe! It was set to Multibyte, but I tried changing it to Unicode and once I did everything compiled and ran flawlessly!
[image of project properties, changing to unicode and boxapp ran!](https://imgur.com/a/jOvQg)

**Comment by Uglyuck** [comment]
I'm having the same error, along with a C2440 error. And have changed the Character Set to both and still get the same error. Not sure if I'm going about it the wrong way or not.
I did an empty C++ project and imported everything in.
First error is on d3dapp.cpp line 387 C2440 error.
	wc.lpszClassName = L"MainWnd";

**Comment by Murzinio** [comment]
You probably have a mix of wide strings and strings and that's why neither option works. In winapi you can wrap your string literals in the __T() or TEXT() macros, this way they will be either wide strings or strings depending on how you compile it.

https://docs.microsoft.com/en-us/windows/desktop/api/winnt/nf-winnt-text
__T() works the same.

**Comment by Uglyuck** [comment]
Thanks! and I figured it out. I had different Character Sets for different platform targets, and when switching to the Win32 target in the settings and setting that as Unicode everything worked.
