### ISSUE TITLE
Is below code has problem in d3dUtil::CompileShader

### ISSUE THREAD

**Issue by GHagi** [d3dcoder/d3d12book#4]
ComPtr<ID3DBlob> byteCode = nullptr;
ComPtr<ID3DBlob> errors;
hr = D3DCompileFromFile(filename.c_str(), defines, D3D_COMPILE_STANDARD_FILE_INCLUDE,
	entrypoint.c_str(), target.c_str(), compileFlags, 0, &byteCode, &errors);

Should I parse byteCode->GetAddressOf() and errors->GetAddressOf() instead of &byteCode and &error? since these are ComPtr type

**Comment by GHagi** [comment]
checked msdn, this is not a issue

**Comment by plasmasnakeneo** [comment]
What resolved this for you?  I am getting an error here and do not know how to fix it.
